### ISSUE TITLE
It cancels all orders only.

### ISSUE THREAD

**Issue by contcat** [N44G/coinDCX_API_custom#1]
It cancels all orders only. did i made any mistake or need to know any thing else.

I run the .py file  online by my api and secrete code.

**Comment by nag-31** [comment]
please share the output
also try to print the open_orders  variable to see if the cancelled orders are being stored properly ,so that they will be opened with same attributes. it works for me and im using it daily.
also download it again n try

**Comment by contcat** [comment]
Please share how to use this file. If possible post screenshots.

Thanks in advance

**Comment by nag-31** [comment]
try the version 2 script i updated. just open the script with some python ide or editor like spyder, pycharm etc , insert  the api key n secret  and run the script .it should work. otherwise i will make a tutorial .

**Comment by contcat** [comment]
On running the V2 script with varies ide's it not working.
it shows only
"[] -----camcel--------"

Please send tutorial

**Comment by nag-31** [comment]
DM me on @Na4g4 twiiter. also u post the screenshot of the output u are getting.

**Comment by nag-31** [comment]
updated the script with examples
